# Generated by Django 4.1.2 on 2022-10-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='departmant',
            new_name='department',
        ),
    ]
