# Generated by Django 4.1.2 on 2022-11-03 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_departmant_researcher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='email',
            field=models.EmailField(default=datetime.datetime(2022, 11, 3, 11, 59, 36, 564917, tzinfo=datetime.timezone.utc), max_length=255, unique=True, verbose_name='email_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Profile Pictures'),
        ),
    ]
